"""Telegram integration models."""

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, String, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.core.db import Base

if TYPE_CHECKING:
    from src.models.staff_user import StaffUser


class TelegramStaffLink(Base):
    """Telegram chat linked to a staff account."""

    __tablename__ = "telegram_staff_links"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    staff_user_id: Mapped[int] = mapped_column(
        ForeignKey("staff_users.id"), nullable=False, unique=True, index=True
    )
    telegram_user_id: Mapped[int] = mapped_column(BigInteger, nullable=False, unique=True, index=True)
    chat_id: Mapped[int] = mapped_column(BigInteger, nullable=False, unique=True, index=True)
    telegram_username: Mapped[str | None] = mapped_column(String(255), nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    linked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    staff_user: Mapped["StaffUser"] = relationship("StaffUser", back_populates="telegram_link")


class TelegramLinkCode(Base):
    """One-time link code generated by an authenticated staff user."""

    __tablename__ = "telegram_link_codes"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    staff_user_id: Mapped[int] = mapped_column(
        ForeignKey("staff_users.id"), nullable=False, index=True
    )
    code: Mapped[str] = mapped_column(String(32), nullable=False, unique=True, index=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    staff_user: Mapped["StaffUser"] = relationship("StaffUser", back_populates="telegram_link_codes")
