"""Add customer_documents table

Revision ID: 4d32881164b2
Revises: 
Create Date: 2026-01-02 18:41:11.532400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4d32881164b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_index(op.f('ix_staff_users_username'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_index(op.f('ix_agreements_agreement_number'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_collateral_person_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_customer_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_driver_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_status'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_agreement_vehicle_segments_agreement_id'), table_name='agreement_vehicle_segments')
    op.drop_index(op.f('ix_agreement_vehicle_segments_vehicle_id'), table_name='agreement_vehicle_segments')
    op.drop_table('agreement_vehicle_segments')
    op.drop_index(op.f('ix_inspection_photos_id'), table_name='inspection_photos')
    op.drop_table('inspection_photos')
    op.drop_index(op.f('ix_customers_first_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_last_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone_primary'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_lookup_values_category'), table_name='lookup_values')
    op.drop_table('lookup_values')
    op.drop_index(op.f('ix_drivers_first_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_last_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_license_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_phone_primary'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_collateral_persons_customer_id'), table_name='collateral_persons')
    op.drop_index(op.f('ix_collateral_persons_first_name'), table_name='collateral_persons')
    op.drop_index(op.f('ix_collateral_persons_id'), table_name='collateral_persons')
    op.drop_index(op.f('ix_collateral_persons_id_number'), table_name='collateral_persons')
    op.drop_index(op.f('ix_collateral_persons_last_name'), table_name='collateral_persons')
    op.drop_index(op.f('ix_collateral_persons_phone_primary'), table_name='collateral_persons')
    op.drop_table('collateral_persons')
    op.drop_index(op.f('ix_vendors_company_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_ledger_entries_agreement_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_at'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_entry_type'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_inspection_templates_id'), table_name='inspection_templates')
    op.drop_index(op.f('ix_inspection_templates_name'), table_name='inspection_templates')
    op.drop_table('inspection_templates')
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_vendor_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('actor_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=22), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('entity_id', sa.INTEGER(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('correlation_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('plate_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('plate_code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('plate_city', sa.VARCHAR(length=50), nullable=True),
    sa.Column('make', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model', sa.VARCHAR(length=50), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=30), nullable=False),
    sa.Column('vehicle_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('car_condition', sa.VARCHAR(length=30), nullable=False),
    sa.Column('motor_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('chassis_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('seats', sa.INTEGER(), nullable=False),
    sa.Column('fuel_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('transmission', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('current_mileage', sa.INTEGER(), nullable=False),
    sa.Column('daily_rate', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('insurance_policy', sa.VARCHAR(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.DATETIME(), nullable=True),
    sa.Column('photo_front', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo_back', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo_left', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo_right', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo_interior', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_vendor_id'), 'vehicles', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=1)
    op.create_table('inspection_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('template_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('checklist_items', sqlite.JSON(), nullable=False),
    sa.Column('damage_categories', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_templates_name'), 'inspection_templates', ['name'], unique=False)
    op.create_index(op.f('ix_inspection_templates_id'), 'inspection_templates', ['id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=14), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=13), nullable=True),
    sa.Column('payment_reference', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('reversed_entry_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['ledger_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_entry_type'), 'ledger_entries', ['entry_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_created_at'), 'ledger_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_agreement_id'), 'ledger_entries', ['agreement_id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.Column('agreement_id', sa.INTEGER(), nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('inspection_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('inspection_datetime', sa.DATETIME(), nullable=False),
    sa.Column('inspector_id', sa.INTEGER(), nullable=True),
    sa.Column('inspector_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('customer_signature', sa.TEXT(), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mileage', sa.INTEGER(), nullable=True),
    sa.Column('fuel_level', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('checklist_results', sqlite.JSON(), nullable=False),
    sa.Column('damage_records', sqlite.JSON(), nullable=False),
    sa.Column('condition_rating', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('photos', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_templates.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_primary', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone_secondary', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bank_account_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bank_account_holder', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_company_name'), 'vendors', ['company_name'], unique=False)
    op.create_table('collateral_persons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_primary', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone_secondary', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('relationship_to_customer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('house_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('wereda', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subcity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=100), nullable=True),
    sa.Column('employer_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('employer_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collateral_persons_phone_primary'), 'collateral_persons', ['phone_primary'], unique=False)
    op.create_index(op.f('ix_collateral_persons_last_name'), 'collateral_persons', ['last_name'], unique=False)
    op.create_index(op.f('ix_collateral_persons_id_number'), 'collateral_persons', ['id_number'], unique=False)
    op.create_index(op.f('ix_collateral_persons_id'), 'collateral_persons', ['id'], unique=False)
    op.create_index(op.f('ix_collateral_persons_first_name'), 'collateral_persons', ['first_name'], unique=False)
    op.create_index(op.f('ix_collateral_persons_customer_id'), 'collateral_persons', ['customer_id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_primary', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone_secondary', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('license_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('license_expiry', sa.DATETIME(), nullable=True),
    sa.Column('license_class', sa.VARCHAR(length=20), nullable=True),
    sa.Column('house_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('wereda', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subcity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_phone_primary'), 'drivers', ['phone_primary'], unique=False)
    op.create_index(op.f('ix_drivers_license_number'), 'drivers', ['license_number'], unique=False)
    op.create_index(op.f('ix_drivers_last_name'), 'drivers', ['last_name'], unique=False)
    op.create_index(op.f('ix_drivers_id_number'), 'drivers', ['id_number'], unique=False)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_first_name'), 'drivers', ['first_name'], unique=False)
    op.create_table('lookup_values',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), nullable=False),
    sa.Column('label', sa.VARCHAR(length=100), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_values_category'), 'lookup_values', ['category'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('business_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tin_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_primary', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone_secondary', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id_expiry', sa.DATETIME(), nullable=True),
    sa.Column('license_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('license_expiry', sa.DATETIME(), nullable=True),
    sa.Column('house_number', sa.VARCHAR(length=50), nullable=True),
    sa.Column('wereda', sa.VARCHAR(length=100), nullable=True),
    sa.Column('subcity', sa.VARCHAR(length=100), nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), nullable=True),
    sa.Column('emergency_contact_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('emergency_contact_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_phone_primary'), 'customers', ['phone_primary'], unique=False)
    op.create_index(op.f('ix_customers_last_name'), 'customers', ['last_name'], unique=False)
    op.create_index(op.f('ix_customers_id_number'), 'customers', ['id_number'], unique=False)
    op.create_index(op.f('ix_customers_first_name'), 'customers', ['first_name'], unique=False)
    op.create_table('inspection_photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inspection_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('mime_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('caption', sa.VARCHAR(length=255), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('checklist_item_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('damage_record_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_photos_id'), 'inspection_photos', ['id'], unique=False)
    op.create_table('agreement_vehicle_segments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agreement_id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('start_datetime', sa.DATETIME(), nullable=False),
    sa.Column('end_datetime', sa.DATETIME(), nullable=False),
    sa.Column('daily_rate', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('start_mileage', sa.INTEGER(), nullable=True),
    sa.Column('end_mileage', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agreement_id'], ['agreements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreement_vehicle_segments_vehicle_id'), 'agreement_vehicle_segments', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_agreement_vehicle_segments_agreement_id'), 'agreement_vehicle_segments', ['agreement_id'], unique=False)
    op.create_table('agreements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('agreement_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('agreement_type', sa.VARCHAR(length=23), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('driver_id', sa.INTEGER(), nullable=True),
    sa.Column('collateral_person_id', sa.INTEGER(), nullable=True),
    sa.Column('pickup_datetime', sa.DATETIME(), nullable=False),
    sa.Column('expected_return_datetime', sa.DATETIME(), nullable=False),
    sa.Column('actual_return_datetime', sa.DATETIME(), nullable=True),
    sa.Column('agreed_daily_rate', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('advance_payment', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('pickup_location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('return_location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pickup_mileage', sa.INTEGER(), nullable=True),
    sa.Column('return_mileage', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('special_terms', sa.TEXT(), nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), nullable=True),
    sa.Column('closed_by_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['collateral_person_id'], ['collateral_persons.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_status'), 'agreements', ['status'], unique=False)
    op.create_index(op.f('ix_agreements_driver_id'), 'agreements', ['driver_id'], unique=False)
    op.create_index(op.f('ix_agreements_customer_id'), 'agreements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_agreements_collateral_person_id'), 'agreements', ['collateral_person_id'], unique=False)
    op.create_index(op.f('ix_agreements_agreement_number'), 'agreements', ['agreement_number'], unique=1)
    op.create_table('staff_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_users_username'), 'staff_users', ['username'], unique=1)
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=1)
    # ### end Alembic commands ###
